[package]
name = "rust_lib_partner_desk"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.102"
bincode = "1.3.3"
enigo = "0.6.1"
flutter_rust_bridge = "=2.12.0"
image = "0.25.10"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.2", features = ["full"] }
xcap = "0.9.4"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
